---
- name: Check and Generate Consul encryption key
  block:

  - name: Generate Consul encryption key
    shell: consul keygen > {{ consul_config_dir }}/encrypt.key
    args:
      creates: "{{ consul_config_dir }}/encrypt.key"

  - name: "Fetch Consul encryption key from consul-master to ansible-master"
    fetch:
      src: "{{ consul_config_dir }}/encrypt.key"
      dest: "{{ consul_fetch_dir }}/certs/"
      flat: yes

  when: consul_master

- name: Wait encryption key to be generated
  wait_for:
    path: "{{ consul_fetch_dir }}/certs/encrypt.key"
  delegate_to: localhost

- set_fact:
    consul_encrypt_key: "{{lookup('file', consul_fetch_dir + '/certs/encrypt.key') }}"
  delegate_to: localhost