---

- name: Create Consul group
  group:
    name: "{{ consul_group }}"
    system: yes
    state: present

- name: Create Consul user
  user:
    name: "{{ consul_user }}"
    shell: /bin/false
    createhome: no
    group: "{{ consul_group }}"
    system: yes
    state: present

- name: Ensure unzip is installed (required by unarchive module)
  package:
    name: unzip
    state: present

- name: Create download directory
  file:
    path: "{{ consul_download_dir }}/{{ consul_version }}"
    state: directory
    recurse: yes

- name: Download Consul
  get_url:
    url: "{{ consul_url }}"
    dest: "{{ consul_download_dir }}/{{ consul_version }}/consul.zip"

- name: Unarchive consul zip
  unarchive:
    src: "{{ consul_download_dir }}/{{ consul_version }}/consul.zip"
    creates: "{{ consul_download_dir }}/{{ consul_version }}/consul"
    dest: "{{ consul_download_dir }}/{{ consul_version }}"
    remote_src: yes

- name: Copy Consul binary
  copy:
    src: "{{ consul_download_dir }}/{{ consul_version }}/consul"
    dest: "{{ consul_install_dir }}/consul_{{ consul_version }}"
    owner: root
    group: root
    mode: 0755
    remote_src: yes

- name: Create Consul symlink
  file:
    src: "{{ consul_install_dir }}/consul_{{ consul_version }}"
    dest: "{{ consul_install_dir }}/consul"
    state: link
    force: yes

- name: Create Consul configuration directory
  file:
    path: "{{ consul_config_dir }}"
    owner: "{{ consul_user }}"
    group: "{{ consul_group }}"
    mode: 0755
    state: directory

- name: Create Consul data directory
  file:
    path: "{{ consul_data_dir }}"
    owner: "{{ consul_user }}"
    group: "{{ consul_group }}"
    mode: 0755
    state: directory

- name: Create consul.service configuration
  template:
    src: consul.service.j2
    dest: /etc/systemd/system/consul.service
    owner: root
    group: root
    mode: 0644
  notify: reload consul

- block:

  - name: Create directory
    file:
      path: /opt/cni/bin
      state: directory

  - name: Extract CNI plugins
    unarchive:
      src: https://github.com/containernetworking/plugins/releases/download/v{{ cni_plugins_version }}/cni-plugins-linux-amd64-v{{ cni_plugins_version }}.tgz
      dest: /opt/cni/bin
      creates: /opt/cni/bin/portmap
      remote_src: yes

  when: cni_plugins_version != ""