---
- name: Run Consul container
  docker_container:
    name: consul
    image: "{{ consul_container_image }}"
    state: started
    detach: True
    restart_policy: always
    network_mode: bridge
    published_ports:
     - "{{ consul_interface_ip }}:{{ consul_outport }}:8500"
    hostname: "{{ ansible_hostname }}"
    command: "{{ consul_container_command }}"
