---
- name: Install pip if needed on Debian
  apt:
    pkg: python-pip
    state: present
    update_cache: yes
  when: "ansible_os_family == 'Debian'"

- name: Install pip if needed on Redhat
  yum:
    pkg: python-pip
    state: present
    update_cache: yes
  when: "ansible_os_family == 'RedHat'"

- name: Install docker container dependencies
  pip:
    executable: /usr/bin/pip
    name: docker-py

- name: Run Consul container
  docker_container:
    name: consul
    image: "{{ consul_container_image }}"
    state: started
    detach: True
    restart_policy: always
    network_mode: bridge
    published_ports:
     - "{{ consul_interface_ip }}:{{ consul_outport }}:8500"
    hostname: "{{ ansible_hostname }}"
    command: "{{ consul_container_command }}"