---
- name: Converge
  hosts: all
  become: true

  tasks:

    - name: "Include grycap.consul"
      include_role:
        name: "ansible-role-consul"
      vars:
        consul_version: "1.17.1"
        consul_config_dir: "/etc/consul"
        consul_dns: false
        consul_join_ips: "{{ groups['front'] | map('extract', hostvars, ['ansible_default_ipv4', 'address']) | list }}"
