---
scenario:
  name: cluster
  test_sequence:
    - dependency
    - destroy
    - create
    - prepare
    - converge
    - idempotence
    - verify
    - destroy
dependency:
  name: galaxy
driver:
  name: docker
verifier:
  name: ansible
platforms:
  - name: server0
    image: "geerlingguy/docker-${MOLECULE_DISTRO:-ubuntu2204}-ansible:latest"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    privileged: true
    pre_build_image: true
    groups:
      - front
    networks:
      - name: "consul"
    network_mode: "consul"
    published_ports:
      - 8501/tcp
  - name: server1
    image: "geerlingguy/docker-${MOLECULE_DISTRO:-ubuntu2204}-ansible:latest"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    privileged: true
    pre_build_image: true
    groups:
      - front
    networks:
      - name: "consul"
    network_mode: "consul"
    published_ports:
      - 8501/tcp
  - name: vnode-1
    image: "geerlingguy/docker-${MOLECULE_DISTRO:-ubuntu2204}-ansible:latest"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    privileged: true
    pre_build_image: true
    groups:
      - wn
    networks:
      - name: "consul"
    network_mode: "consul"
    published_ports:
      - 8501/tcp
provisioner:
  name: ansible
  playbooks:
    converge: ${MOLECULE_PLAYBOOK:-converge.yml}
  inventory:
    group_vars:
      front:
        consul_server: true
        consul_bootstrap_expect: 2
        consul_master: true
      wn:
        consul_server: false
        consul_master: false
