---
- name: Verify
  hosts: all
  become: true

  tasks:

    - name: Test
      command: consul members
      register: nodes

    - debug:
        var: nodes.stdout

    - name: Check service running
      assert:
        that:
          - "'server0' in nodes.stdout"
          - "'server1' in nodes.stdout"
          - "'vnode-1' in nodes.stdout"
          - "'alive   server' in nodes.stdout"
          - "'alive   client' in nodes.stdout"
        fail_msg: "Error getting members"
        success_msg: "Consul installed and running"

