---
- name: Verify
  hosts: all
  become: true

  tasks:

    - name: Test
      command: consul members
      register: nodes

    - name: Check service running
      fail:
        msg: "Error getting members"
      when: "'vnode-1' not in nodes.stdout" 

